#!/bin/bash
TEMPLATE_DIRECTORY=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
SOURCE_DIRECTORY='/usr/local/bin"

eval cd $SOURCE_DIRECTORY

echo Creating symbolic links
sudo ln -s "$TEMPLATE_DIRECTORY/templater" templater
echo Done
